name: My First Workflow
on:
  push:
    branches:
      - main
jobs:
  myFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: printenv
      - name: My Second Step
        run: |
          echo "Thurmans GHA"
          echo "Hello" > file.txt
          ls
          cat file.txt
      - name: Speep Step
        run: sleep 5
      - name: My First Action
        uses: actions/checkout@v6.0.1
      - name: ls repo
        run: |
          ls
        
